pool: Hosted Windows 2019 with VS2019
name: 1.0.0$(Rev:.r)

steps:

- checkout: self

- task: DotNetCoreCLI@2
  name: 'Build'
  inputs:
    command: 'build'
    arguments: '-c Release'
    configuration: 'Release'
    feedsToUse: 'select'
    versioningScheme: 'off'

- task: VSTest@2
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: '**\*.Tests*.dll
      !**\*TestAdapter.dll
      !**\obj\**'
    searchFolder: '$(System.DefaultWorkingDirectory)'
    codeCoverageEnabled: true

- task: DotNetCoreCLI@2
  name: 'Pack'
  inputs:
    command: 'pack'
    feedsToUse: 'select'
    packagesToPack: '**/*.csproj'
    configuration: 'Release'
    versioningScheme: 'byBuildNumber'

- task: DotNetCoreCLI@2
  name: 'Push'
  inputs:
    command: 'push'
    feedsToUse: 'select'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: 'Packages'
    versioningScheme: 'off'